# Generated by Django 5.2.7 on 2025-11-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('DF', 'Draft')], default='DF', max_length=2),
        ),
    ]
